### ISSUE TITLE
Limits of operators should be part of the API

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strus#51]
Maximal number of (in this case) union operator is hard-coded to 64.

```
error creating 'union' iterator: number of arguments of union out of range (> 64)
```

in src/queryproc/iterator/postingIteratorUnion.cpp

```
if (args_.size() > 64)

throw strus::runtime_error( _TXT( "number of arguments of union out of range (> %u)"), 64);
```

This should be a constant in a header file (DRY) and it should be configurable at
runtime because some queries can be really big. :-)

Other operators (and functions) affected?

**Comment by patrickfrey** [comment]
I put all constants of this kind into the corresponding header files. Besides 'union' also the 'contains' operator is affected. And the weighting function BM25pff plus the summarizers MatchPhrase and AccumulateVariables. The main reasons for these constants are bitsets implemented as 64bit integer instead of dynamic bitsets and the use of some static arrays in the BM25pff weighting.

**Comment by patrickfrey** [comment]
Done
